name: Deploy Lambda to S3

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch when pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest #virtual ubuntu machine provided by github to run 

    steps:
      # Step 1: pulls latest github code to the unbuntu vm 
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticates GitHub Actions to interact with your AWS account using stored GitHub secrets.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      # Step 3: Zip the Lambda function
      - name: Zip Lambda function
        run: |
          zip -r function.zip main.py

      # Step 4: Upload ZIP file to S3
      - name: Upload to S3
        run: aws s3 cp function.zip s3://azizaws.com/lambda/function.zip

      # Step 5: Update AWS Lambda Function
      - name: Update AWS Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name CloudResumeTestAPI \
            --region us-east-1 \
            --s3-bucket azizaws.com \
            --s3-key lambda/function.zip

